### ISSUE TITLE
Allow root path in Github repository

### ISSUE THREAD

**Issue by vincentvanderweele** [zeplin/connected-components-beta-issues#1]
**Problem description**

The current github configuration in `components.json` allows you to set `url`, `repository`, and `branch`, leading to the url

```
<url><repository>/blob/<branch>/<filePath>
```

This is assuming that a Github repository maps one-to-one to a Zeplin project. However, we use a mono-repo in Github, so the actual url to a resource in a project is

```
<url><repository>/blob/<branch>/<projectPath>/<componentPath>
```

**Feature request**

Could you add an optional configuration value `path` to the Github configuration object that allows referencing projects that are not in the root of the Github repository?

**Example usage**

```json
{
    "projects": [],
    "styleguides": ["..."],
    "components": [...],
    "github": {
        "repository": "example/repository-name",
        "path": "example-project/frontend"
    }
}
```

leading to the url

```
https://github.com/example/repository-name/blob/master/example-project/frontend/<componentPath>
```

**Comment by yuqu** [comment]
Hey @vincentvanderweele 👋  ,

We have added a new property named as `path` on v0.2.6. You can update your @zeplin/cli package and start to use it. 🎉 

It works exactly as your usage example, you can checkout the [updated documentation](https://zpl.io/connected-components-onboarding) for the details.

Huge thanks for the suggestion 🙏

**Comment by vincentvanderweele** [comment]
Works like a charm! Thanks @yuqu!
