### ISSUE TITLE
Babel error when using `zeplin connect -p @zeplin/cli-connect-react-plugin`

### ISSUE THREAD

**Issue by samwalshnz** [zeplin/connected-components-beta-issues#2]
When running `zeplin connect -p @zeplin/cli-connect-react-plugin`, I'm currently getting this error:

```
Connecting components to Zeplin components failed.

    [BABEL] unknown: Preset /* your preset */ requires a filename to be set when babel is called directly,

babel.transform(code, { filename: 'file.ts', presets: [/* your preset */] });

See https://babeljs.io/docs/en/options#filename for more information.
```

Any ideas?

**Comment by yuqu** [comment]
Hey @samwalshnz 👋 , thanks for reaching out.

My guess is there might be a problem with one of the components on the config file. Could you check `components.path[*]` values on your `.zeplin/components.json` file? You can share it with us to investigate as well if that is okay for you.

Could you also install the last update on `@zeplin/cli` package (v0.2.6) and try to do it again with `--verbose` flag and share the output if the problem occurs again?

```
zeplin connect -p @zeplin/cli-connect-react-plugin --verbose
```

**Comment by yuqu** [comment]
Hi again @samwalshnz, do you have any progress on the issue?

**Comment by yuqu** [comment]
Hi Sam, 

I'm closing the issue for inactivity.

[Connected Components](https://zpl.io/connected-components) is out, please follow the [new documentation](https://github.com/zeplin/connected-components-docs) to reiterate through the process.

If you still have any problems, feel free to create a new issue on https://github.com/zeplin/cli or https://github.com/zeplin/cli-connect-react-plugin/ repositories.
