### ISSUE TITLE
cli connect -  Cannot read property 'name' of undefined

### ISSUE THREAD

**Issue by thomaswelton** [zeplin/connected-components-beta-issues#3]
Running `zeplin connect -p @zeplin/cli-connect-react-plugin`

Give this output 

```
Connecting components to Zeplin components failed.

    /Users/thomaswelton/.nvm/versions/node/v10.16.3/lib/node_modules/@zeplin/cli-connect-react-plugin/dist/template/base.pug:16
        14| 
        15| mixin property(name, type)
      > 16|     if type.name === "union"
        17|         |   #{name}={union[
        18|         +propertyValues(type.value)
        19|         | }]

    Cannot read property 'name' of undefined
```

Based on a components.json file like

```
{
    "projects": [
        "ourId"
    ],
    "styleguides": [],
    "components": [
        {
            "path": "src/components/Button/index.js",
            "zeplinNames": [
                "Buttons/Small/Standard/Standard primary button"
            ],
            "storybook": {
                "kind": "Button",
                "stories": ["default", "primary"]
            }
        }
    ],
    "links": [
        {
            "type": "storybook",
            "url": "https://example.com"
        }
    ]
}
```

**Comment by yuqu** [comment]
Hey @thomaswelton 👋 , thanks for reaching out.

Does your component have any PropType fields? If it does, could you share what kind of PropTypes are those?

**Comment by thomaswelton** [comment]
We use FlowTypes for Props and use a babel plugin https://www.npmjs.com/package/babel-plugin-flow-react-proptypes to generate PropTypes from our flow types.

**Comment by yuqu** [comment]
I found out the problem when working with Flow types. We're working on it, I'll update you when the fix is ready.

**Comment by jerrymao15** [comment]
Getting similar problems here in our project, even with our PropType fields commented out. Not using any other type of type checking as well. Our `components.json` is as follows:

```
{
    "projects": [],
    "styleguides": [
        "idHere"
    ],
    "components": [
        {
            "path": "spas/mayhem/src/design/Button.js",
            "zeplinNames": [
                "Button/full/32px ",
                "Button/full/40px",
                "Button/full/48px",
                "Button/full/56px",
                "Button/full/64px"
            ]
        },
        {
            "path": "spas/mayhem/src/design/OutlineButton.js",
            "zeplinNames": [
                "Button/line/32px",
                "Button/line/40px",
                "Button/line/48px",
                "Button/line/56px",
                "Button/line/64px"
            ]
        }
    ]
}
```

**Comment by yuqu** [comment]
@thomaswelton @jerrymao15 
We have published a new version to the react plugin package:`@zeplin/cli-connect-react-plugin@0.2.1`

Could you upgrade the package and give it a try?

**Comment by thomaswelton** [comment]
Thanks that's working for us now

**Comment by gucomecan** [comment]
I am using typescript with React native and instead of Button.jsx I have Button.tsx. The error is the same(tried with 0.2.1 and the latest version of `@zeplin/cli-connect-react-plugine`

**Comment by yuqu** [comment]
Hi @gucomecan,

Could you checkout https://github.com/zeplin/cli-connect-react-plugin/issues/10 and https://github.com/zeplin/cli-connect-react-plugin/issues/13? You might be having the same with one of those. If those are not related to your problem, could you open an issue with details about your component on https://github.com/zeplin/cli-connect-react-plugin repository?
