### ISSUE TITLE
Feature Request: Create Vue CLI plugin

### ISSUE THREAD

**Issue by jackkoppa** [zeplin/connected-components-beta-issues#4]
We love the beta so far! Improves so much of our workflow @ Politico. Our shared components are written in Vue, which Storybook does a great job of supporting. We wanted to check if there are any plans to create the Vue equivalent for `@zeplin/cli-connect-react-plugin`. In the [documentation that comes through on NPM](https://www.npmjs.com/package/@zeplin/cli#custom-plugins), it looks like custom plugins will be supported, though the associated repo appears to still be private (totally understandable). We'd love the "snippets in Zeplin" benefit, and our CI pipeline is already setup well to add that step to keep them up-to-date.

If there are already plans for a Vue plugin, is there anything we can help contribute to?

**Comment by borulday** [comment]
Hi @jackkoppa! Thanks for your kind words 🙌 Zeplin CLI and the plugins will be open-source and Zeplin CLI will support custom plugins as you already realized. In the short-term, we aim that developers who love Zeplin create some plugins for the community's needs. So, we're completely open-minded about getting some help--even more than help! 😄 

Since you already talked about all these with my teammate from Zeplin support I want to keep the explanation short. 😅 

As I know, my teammate shared with you Zeplin React plugin and a plugin template to help you while building a Vue plugin. If you need any help just let us know!

**Comment by jackkoppa** [comment]
Sounds great! Yup, thanks @borulday, I'll be giving the Vue plugin at least an initial shot, and will check in with questions 👍

**Comment by jackkoppa** [comment]
Hi @borulday - it's been refreshingly simple! Thanks for the great docs. A basic version is working here: [GitHub](https://github.com/jackkoppa/zeplin-cli-connect-plugin-vue), [npm](https://www.npmjs.com/package/zeplin-cli-connect-plugin-vue)

No complaints so far, and it might honestly work well enough for us. I'll probably add handling for Vue `<slots>` and maybe `@events`, which are both documented by the `vue-docgen-api` that makes this very easy. I'll raise one issue in this repo; we'd prefer to use `PrismLang.HTML` over `PrismLang.JSX` to describe Vue templates, but it looks like Zeplin doesn't yet do syntax highlighting for things described as HTML?

Thanks again - looks like you've got a great ecosystem on your hands 🙌

**Comment by yuqu** [comment]
@jackkoppa Great work! 🎉 

I'm surprised that HTML syntax highlighting is not working. There might be an issue on the client app, or maybe the constant defined on PrismLang enum is wrong somehow. We're are going to investigate it. In the meantime, could you try it with PrismLang.Markup and see if that works?

We would appreciate if you have any ideas or feedbacks to expand the capabilities of the plugin interface.

**Comment by jackkoppa** [comment]
Thanks @yuqu - `PrismLang.Markup` seems to work perfectly. No concerns about just sticking with that; covers all the syntax that we'd be interested in for #6 

And yup, will certainly let you know if there are any issues I run into; it's quite nice in that the info you need to expose is pretty limited, so long as we can get the file path of the component. `description`, `lang`, and `snippet` all seem to be working as I'd expect.

For now, I published an initial `0.1.0` version on npm; seems to work well enough that people could make initial use of it. Wonderfully quick, that

**Comment by yuqu** [comment]
Since https://github.com/zeplin/connected-components-beta-issues/issues/6 is now closed, I'm closing this issue as well.

Thanks again for your efforts 🎉
