### ISSUE TITLE
Support PrismLang.HTML for syntax highlighting

### ISSUE THREAD

**Issue by jackkoppa** [zeplin/connected-components-beta-issues#6]
For Vue "Single File Components" (SFCs), the template portion of the component lives in a `<template>` block. This template area is not technically HTML, because there are plenty of Vue-specific syntaxes, like `:attribute=""` for a dynamic attribute, or `@event=""` for event handling.

However, it is closer to HTML than to JSX, so we'd like the snippet lang to be treated as HTML; it generally leads to better syntax highlighting than JSX. 

When we set `PrismLang.ReactJSX`, we get pretty decent highlighting:
![Screen Shot 2019-12-06 at 3 52 44 PM](https://user-images.githubusercontent.com/14101491/70355727-db091300-1840-11ea-89d8-3e27b53f6999.png)

But when we try `PrismLang.HTML`, we get no highlighting at all:
![Screen Shot 2019-12-06 at 3 56 54 PM](https://user-images.githubusercontent.com/14101491/70355873-26bbbc80-1841-11ea-813f-9e80393b1078.png)

**Is it possible to enable HTML syntax highlighting with Prism?** Let me know if you need any other details; can easily replicate with this repo and the snapshot components there: https://github.com/jackkoppa/zeplin-cli-connect-plugin-vue

**Comment by jackkoppa** [comment]
Per #4, using `PrismLang.Markup` works as well as I'd hope :+1:

So not having `PrismLang.HTML` is hardly a blocker; issue can be closed if need be

**Comment by yuqu** [comment]
With the latest beta update on macOS app, using `PrismLang.HTML` works now.
