### ISSUE TITLE
Angular support

### ISSUE THREAD

**Issue by TheSonOfThomp** [zeplin/connected-components-beta-issues#8]
It'd be really great to have first party Angular support.

 Barring first party support, docs for how the community might create one would also be nice

**Comment by yuqu** [comment]
Hey Adam,

We have a plugin for angular: [@zeplin/cli-connect-angular-plugin](https://www.npmjs.com/package/@zeplin/cli-connect-angular-plugin). It has a couple of issues that we work on right now but you can try the published version.

Docs for plugin development are going to be released in the following days 🥂

**Comment by TheSonOfThomp** [comment]
Thanks Yucel,

I tried installing that plugin, but it looks like I need access to the Github repo?

Error message:
```bash
npm ERR! Error while executing:
npm ERR! /usr/bin/git ls-remote -h -t ssh://git@github.com/yuqu/compodoc.git
npm ERR! 
npm ERR! git@github.com: Permission denied (publickey).
npm ERR! fatal: Could not read from remote repository.
npm ERR! 
npm ERR! Please make sure you have the correct access rights
npm ERR! and the repository exists.
npm ERR! 
npm ERR! exited with error code: 128
```

**Comment by yuqu** [comment]
Oh, the plugin depends on a forked version of an angular tool and apparently we mistakenly set it to the ssh git URL instead of http 👀 . Anyway, we were planning for a release tomorrow for the issues I mentioned, this is also going to be fixed on that release. Sorry for the hassle 😅 I'll ping you here when it is published.

**Comment by yuqu** [comment]
Hey @TheSonOfThomp, sorry for the late response. We published a new version which also addresses the issue you had. You can now give it a try, looking forward for your feedback 🤞

**Comment by yuqu** [comment]
Hi Adam, 

I'm closing the issue for inactivity.

[Connected Components](https://zpl.io/connected-components) is out, please follow the [new documentation](https://github.com/zeplin/connected-components-docs) to reiterate through the process.

If you still have any problems, feel free to create a new issue on https://github.com/zeplin/cli or https://github.com/zeplin/cli-connect-angular-plugin/ repositories.
